name: Pipeline CI/CD - Estação Meteorológica

on:
  push:
    branches:
      - main

jobs:

  integracao-continua:
    name: Integração Contínua
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Executar validação Python
        run: |
          python scripts/validar_dados.py

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Validar Terraform
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate


  entrega-continua:
    name: Entrega Contínua
    needs: integracao-continua
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: |
          docker build -t estacao-meteorologica:latest .

      - name: Scan de vulnerabilidades com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'estacao-meteorologica:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload do arquivo para o S3
        run: |
          aws s3 cp dados_clima.txt s3://estacao-meteorologica-ingrid-v2-2026/

      - name: Finalização
        run: echo "Pipeline executado com sucesso!"